server:
  port: 8023
  servlet:
    context-path: /springboot
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 123456Aa
  # thymeleaf模板配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
mybatis:
  mapper-locations: classpath:mapping/*.xml
